# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='token_last_expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
