# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_volunteer_token_last_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='token_last_expired',
        ),
    ]
