# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.SmallIntegerField()),
                ('date', models.DateField(blank=True)),
                ('status', models.CharField(blank=True, default='OK', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.ActivityType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='elder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elders.Elder'),
        ),
        migrations.AddField(
            model_name='activity',
            name='volunteer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
