# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('date', models.DateField(default=datetime.date(2017, 7, 27))),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('elder', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elders.Elder')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.ActivityType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='volunteer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
