# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
