# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 06:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='user',
            new_name='volunteer',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.date(2017, 7, 9)),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
