# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lbfe_app', '0002_auto_20170716_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 16, 27, 21, 722524, tzinfo=utc)),
        ),
    ]
