# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbfe_app', '0004_auto_20170716_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
