# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
