# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elder_Volunteer',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='elder',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='elder_volunteer',
            name='elder',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elders.Elder'),
        ),
        migrations.AddField(
            model_name='elder_volunteer',
            name='volunteer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
